## Importing Libraries

In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Data Preprocessing

### Training Image Preprocessing

In [7]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [8]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [9]:
training_set


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [10]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[180.25 176.25 190.25]
   [175.5  171.5  185.5 ]
   [171.5  167.5  181.5 ]
   ...
   [151.   145.   157.  ]
   [140.5  134.5  146.5 ]
   [146.5  140.5  152.5 ]]

  [[176.5  172.5  186.5 ]
   [172.25 168.25 182.25]
   [176.75 172.75 186.75]
   ...
   [151.25 145.25 157.25]
   [132.   126.   138.  ]
   [136.5  130.5  142.5 ]]

  [[176.5  172.5  186.5 ]
   [175.75 171.75 185.75]
   [178.75 174.75 188.75]
   ...
   [144.   138.   150.  ]
   [134.5  128.5  140.5 ]
   [155.   149.   161.  ]]

  ...

  [[163.75 157.75 171.75]
   [168.75 162.75 176.75]
   [169.75 163.75 177.75]
   ...
   [125.25 119.25 131.25]
   [132.75 126.75 138.75]
   [133.25 127.25 139.25]]

  [[174.75 168.75 182.75]
   [167.5  161.5  175.5 ]
   [168.25 162.25 176.25]
   ...
   [134.25 128.25 140.25]
   [124.75 118.75 130.75]
   [132.   126.   138.  ]]

  [[170.5  164.5  178.5 ]
   [169.25 163.25 177.25]
   [172.75 166.75 180.75]
   ...
   [126.   120.   132.  ]
   [130.   124.   136.  ]
   [135.75 129.75 14